# 声明构建语言环境
language: node_js

notifications:
    on_success: never

# nodejs语言版本
node_js:
  - "14"

#缓存
cache: npm

# 安装
install:
  - npm i

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  email: gongxq95@gmail.com
  name: BetaMee
  target_branch: master
  local_dir: public
  on:
    branch: source-code