# 声明构建语言环境
language: node_js

notifications:
    on_success: never

# nodejs语言版本
node_js:
  - "10"

#缓存
cache: yarn

# 安装
install:
  - yarn

# !执行脚本，这里有问题，暂时只能手动部署
script:
  - yarn run deploy

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep_history: true
#   on:
#     branch: master